# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: blog
description: My Personal Site/Blog
author:
  name: Raoul DIFFOUO
  email: diraulo@gmail.com
  email_md5: 608eda1753a268741c7d46efa337ffa2
  bio: Web Developer - Robotic Hobbyist
  contact:
    basic:
      website: diraulo.me
      email: hello@diraulo.me
      email_txt: hello[at]diraulo[dot]me
      phone: +27 (0) 12 341 7228
      mobile: +27 (0) 71 071 5114
    social:
      github: diraulo
      twitter: diraulo
      linkedin: diraul
  skills:
    - name: AngularJS
      level: 60
    - name: HTML5 & CSS3
      level: 90
    - name: Javascript
      level: 70
    - name: NodeJS
      level: 55
    - name: Ruby
      level: 65
    - name: Ruby on Rails
      level: 50
  portfolio:
    - name: ASE House4Hack Roadshow
      url: http://aseroadshow.house4hack.co.za/
      thumbnail: aseroadshow
    - name: Yummygraphs
      url: http://www.yummygraphs.co.za/
      thumbnail: yummy.png

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

permalink: pretty
paginate: 10
paginate_path: 'page:num'

# Markdown library
markdown: kramdown
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   use_coderay: false
#   coderay:
#     coderay_wrap: div
#     coderay_line_numbers: inline
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: style

pygments: true
